// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 moved seed config out of package.json's "prisma.seed" field
    // (which it no longer reads) and into here. package.json's "prisma.seed"
    // is left in place too for tooling/readability, but this is what Prisma
    // CLI actually uses to run `npx prisma db seed`.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Direct (unpooled) connection for Migrate/introspection, per Neon's guidance.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
